DROP TABLE categories CASCADE;
DROP TABLE cust_hist CASCADE;
DROP TABLE customers CASCADE;
DROP TABLE inventory CASCADE;
DROP TABLE orderlines CASCADE;
DROP TABLE orders CASCADE;
DROP TABLE products CASCADE;
DROP TABLE reorder CASCADE;

